[[plugin]]
id = "bioinformatist/d2r-tz"
name = "暗黑2恐怖地带"
version = "0.1.3"
author = "bioinformatist"
license = "MIT"
icon = "skull"
description = "显示术士君临在线恐怖地带及经验、掉落评级。"
plugin_api = 24
tags = ["gaming", "diablo"]
dependencies = ["xdg-open"]
